# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=8)),
            ],
        ),
    ]
