# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actName', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('ingress', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgNumber', models.CharField(max_length=9)),
                ('orgName', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
