# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='registration',
            new_name='registration_required',
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='videos',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
