# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0002_auto_20170224_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
