# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0002_activity_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Organisation')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Activity')),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Users')),
                ('orgNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipateIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Activity')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Users')),
            ],
        ),
    ]
