# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0003_employedin_hosts_participatein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='actName',
            new_name='activityName',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgNumber',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
