# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0004_auto_20170301_1227'),
        ('skalvi', '0006_auto_20170301_1335'),
    ]

    operations = [
    ]
