# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0007_merge_20170302_1311'),
        ('skalvi', '0007_merge_20170307_1153'),
    ]

    operations = [
    ]
