# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0007_merge_20170302_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instagram',
            field=models.TextField(blank=True),
        ),
    ]
