# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0009_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatein',
            name='user_profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skalvi.UserProfile'),
            preserve_default=False,
        ),
    ]
