# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0009_userprofile_is_active'),
        ('skalvi', '0008_activity_instagram'),
    ]

    operations = [
    ]
