# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0010_merge_20170310_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='videos',
            field=models.ImageField(blank=True, max_length=255, upload_to='videos/'),
        ),
    ]
