# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0010_merge_20170310_0937'),
        ('skalvi', '0010_merge_20170310_1350'),
    ]

    operations = [
    ]
