# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0011_auto_20170310_1557'),
        ('skalvi', '0011_merge_20170310_1457'),
    ]

    operations = [
    ]
