# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0012_merge_20170313_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ukjent'), (1, 'Skating'), (2, 'Klatring'), (3, 'Ski'), (4, 'Svømming')], default=0),
        ),
    ]
