# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0010_participatein_user_profile_id'),
        ('skalvi', '0012_merge_20170313_1449'),
    ]

    operations = [
    ]
