# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0013_merge_20170314_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='facebookID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
