# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0013_activity_activitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='suitedForType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ukjent'), (1, 'Tilpasset 1'), (2, 'Tilpasset 2'), (3, 'Tilpasset 3'), (4, 'Tilpasset 4')], default=0),
        ),
    ]
