# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0014_auto_20170315_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='facebookInfo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
