# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0015_activity_facebookinfo'),
        ('skalvi', '0015_merge_20170320_1000'),
    ]

    operations = [
    ]
