# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0016_merge_20170320_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
