# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0016_merge_20170320_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='profileId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='skalvi.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hosts',
            name='adminId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
