# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0016_merge_20170320_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='aktordatabase',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgNumber',
            field=models.CharField(max_length=9),
        ),
    ]
