# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:27
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0017_auto_20170322_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='aktordatabase',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aktordatabase',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
