# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0017_activity_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
