# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0017_auto_20170322_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='adminId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='profileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.UserProfile'),
        ),
    ]
