# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skalvi', '0019_userprofile_is_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='orgName',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='orgNumber',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='phone',
        ),
        migrations.AddField(
            model_name='organisation',
            name='aktordatabase',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skalvi.UserProfile'),
        ),
    ]
