# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0019_auto_20170322_1523'),
        ('skalvi', '0018_auto_20170322_1309'),
    ]

    operations = [
    ]
