# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0020_auto_20170322_1410'),
        ('skalvi', '0020_merge_20170323_1113'),
    ]

    operations = [
    ]
