# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skalvi', '0020_merge_20170323_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.Activity')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skalvi.UserProfile')),
            ],
        ),
    ]
