# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0021_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='number_of_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
