# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0022_auto_20170324_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentary',
            name='date',
            field=models.DateField(),
        ),
    ]
