# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0023_auto_20170324_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='userProfile_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
