# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0024_commentary_userprofile_name'),
        ('skalvi', '0021_merge_20170323_1121'),
    ]

    operations = [
    ]
