# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0025_merge_20170328_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='number_of_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
