# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0026_auto_20170328_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(default='hei@hei.no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Nordmann', max_length=30),
            preserve_default=False,
        ),
    ]
