# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0027_auto_20170329_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aktordatabase',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_provider',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=60),
        ),
    ]
