# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0027_auto_20170330_1251'),
        ('skalvi', '0028_auto_20170329_1528'),
    ]

    operations = [
    ]
