# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0029_merge_20170330_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assistants_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='assistants_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
