# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0031_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
