# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0031_auto_20170405_0840'),
        ('skalvi', '0031_follows'),
    ]

    operations = [
    ]
