# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0032_merge_20170405_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='provider',
            field=models.TextField(blank=True, null=True),
        ),
    ]
