# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skalvi', '0032_auto_20170405_1350'),
        ('skalvi', '0033_auto_20170405_1400'),
    ]

    operations = [
    ]
